AllCops:
  NewCops: enable
  DisabledByDefault: false
  DisplayCopNames: true
  TargetRubyVersion: 2.6.2
  Exclude:
    - 'bin/*'
    - 'spec/spec_helper.rb'
    - 'eps-rapid.gemspec'
Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Metrics/ClassLength:
  Max: 120
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/PerceivedComplexity:
  Max: 12
Metrics/LineLength:
  Max: 120
Lint/UselessAssignment:
  Enabled: true
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: true
  Max: 35
Naming/FileName:
  Enabled: false