module EpsRapid
  module HttpStatusCodes
    HTTP_OK_CODE = 200
    HTTP_BAD_REQUEST_CODE = 400
    HTTP_UNAUTHORIZED_CODE = 401
    HTTP_FORBIDDEN_CODE = 403
    HTTP_NOT_FOUND_CODE = 404
    HTTP_SESSION_GONE_CODE = 410
    HTTP_UPGRADE_REQUIRED_CODE = 426
    HTTP_TOO_MANY_REQUESTS_CODE = 429
  end
end